export type Listing = {
  id: string;
  title: string;
  price: string;
  priceNum: number;
  area: string;
  district: string;
  type: string;
  image: string;
  tags: string[];
  verified: boolean;
  rating: number;
  description: string;
  amenities: string[];
};

export const LISTINGS: Listing[] = [
  {
    id: "1",
    title: "Studio hiện đại Quận 1",
    price: "8.5 tr/tháng",
    priceNum: 8500000,
    area: "28 m²",
    district: "Quận 1, TP.HCM",
    type: "Studio",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80&fit=crop",
    tags: ["AI Verified", "Full nội thất", "Thang máy"],
    verified: true,
    rating: 4.9,
    description: "Căn hộ studio cao cấp ngay trung tâm Quận 1, view thành phố tuyệt đẹp. Đầy đủ nội thất hiện đại, an ninh 24/7.",
    amenities: ["Wifi tốc độ cao", "Máy lạnh", "Máy giặt", "Bếp đầy đủ", "Smart TV", "Hầm xe"],
  },
  {
    id: "2",
    title: "1PN ban công rộng Bình Thạnh",
    price: "6.2 tr/tháng",
    priceNum: 6200000,
    area: "40 m²",
    district: "Bình Thạnh, TP.HCM",
    type: "1 Phòng ngủ",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80&fit=crop",
    tags: ["Mới đăng", "Ban công", "Gần Metro"],
    verified: true,
    rating: 4.7,
    description: "Căn hộ 1 phòng ngủ thoáng mát với ban công rộng view thành phố. Gần Metro số 1, tiện di chuyển.",
    amenities: ["Ban công rộng", "Wifi", "Máy lạnh", "Tủ lạnh", "Hầm xe", "Gym"],
  },
  {
    id: "3",
    title: "2PN cao cấp Thủ Đức",
    price: "12 tr/tháng",
    priceNum: 12000000,
    area: "65 m²",
    district: "TP. Thủ Đức, TP.HCM",
    type: "2 Phòng ngủ",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80&fit=crop",
    tags: ["Hot", "Pool", "2PN"],
    verified: false,
    rating: 4.5,
    description: "Căn hộ 2 phòng ngủ rộng rãi trong khu phức hợp cao cấp. Hồ bơi, gym, khu BBQ.",
    amenities: ["Hồ bơi", "Gym", "BBQ", "Wifi", "2 máy lạnh", "2 WC", "Hầm xe"],
  },
  {
    id: "4",
    title: "Studio cozy Quận 7",
    price: "7 tr/tháng",
    priceNum: 7000000,
    area: "30 m²",
    district: "Quận 7, TP.HCM",
    type: "Studio",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80&fit=crop",
    tags: ["AI Verified", "Gần RMIT", "Yên tĩnh"],
    verified: true,
    rating: 4.8,
    description: "Studio ấm cúng gần trường RMIT và Lotte Mart. Yên tĩnh, an ninh, phù hợp sinh viên và người đi làm.",
    amenities: ["Wifi", "Máy lạnh", "Tủ lạnh", "Bếp từ", "Smart TV"],
  },
  {
    id: "5",
    title: "Penthouse view sông Quận 4",
    price: "25 tr/tháng",
    priceNum: 25000000,
    area: "90 m²",
    district: "Quận 4, TP.HCM",
    type: "Penthouse",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80&fit=crop",
    tags: ["Penthouse", "View sông", "Luxury"],
    verified: true,
    rating: 5.0,
    description: "Penthouse sang trọng view toàn cảnh sông Sài Gòn. Nội thất cao cấp, dịch vụ concierge 24/7.",
    amenities: ["View sông", "Jacuzzi", "Terrace", "Butler service", "Gym riêng", "3 máy lạnh"],
  },
  {
    id: "6",
    title: "1PN giá tốt Gò Vấp",
    price: "4.5 tr/tháng",
    priceNum: 4500000,
    area: "35 m²",
    district: "Gò Vấp, TP.HCM",
    type: "1 Phòng ngủ",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=80&fit=crop",
    tags: ["Giá tốt", "Gần chợ", "Có gác"],
    verified: false,
    rating: 4.2,
    description: "Phòng 1PN tiện nghi, giá hợp lý. Gần chợ Gò Vấp và nhiều tiện ích xung quanh.",
    amenities: ["Wifi", "Máy lạnh", "Nội thất cơ bản", "WC riêng"],
  },
  {
    id: "7",
    title: "Studio luxury Quận 3",
    price: "9.8 tr/tháng",
    priceNum: 9800000,
    area: "32 m²",
    district: "Quận 3, TP.HCM",
    type: "Studio",
    image: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=600&q=80&fit=crop",
    tags: ["AI Verified", "Luxury", "Trung tâm"],
    verified: true,
    rating: 4.8,
    description: "Studio sang trọng giữa trung tâm Quận 3. Thiết kế tối giản hiện đại, ánh sáng tự nhiên tràn ngập.",
    amenities: ["Wifi 500Mbps", "Máy lạnh Daikin", "Máy giặt sấy", "Bếp từ", "Điều chỉnh đèn thông minh"],
  },
  {
    id: "8",
    title: "2PN gia đình Quận 10",
    price: "10.5 tr/tháng",
    priceNum: 10500000,
    area: "58 m²",
    district: "Quận 10, TP.HCM",
    type: "2 Phòng ngủ",
    image: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=600&q=80&fit=crop",
    tags: ["Gần bệnh viện", "An ninh 24/7", "Gần trường"],
    verified: true,
    rating: 4.6,
    description: "Căn hộ 2PN rộng rãi, phù hợp gia đình trẻ. Gần bệnh viện Chợ Rẫy, trường học, siêu thị.",
    amenities: ["2 phòng ngủ", "Bếp riêng", "Wifi", "Máy lạnh", "Tủ lạnh to", "Hầm xe 2 xe"],
  },
  {
    id: "9",
    title: "Studio view hồ bơi Bình Chánh",
    price: "5.5 tr/tháng",
    priceNum: 5500000,
    area: "26 m²",
    district: "Bình Chánh, TP.HCM",
    type: "Studio",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80&fit=crop",
    tags: ["View pool", "Mới xây", "Gym"],
    verified: false,
    rating: 4.3,
    description: "Studio mới xây, view thẳng hồ bơi. Khu dân cư yên tĩnh, phù hợp người làm việc từ xa.",
    amenities: ["Hồ bơi", "Gym", "Wifi", "Máy lạnh", "Khu vực BBQ"],
  },
  {
    id: "10",
    title: "1PN cao cấp Phú Nhuận",
    price: "8 tr/tháng",
    priceNum: 8000000,
    area: "45 m²",
    district: "Phú Nhuận, TP.HCM",
    type: "1 Phòng ngủ",
    image: "https://images.unsplash.com/photo-1551361415-69c87624334f?w=600&q=80&fit=crop",
    tags: ["AI Verified", "Cao cấp", "Gần sân bay"],
    verified: true,
    rating: 4.7,
    description: "Căn hộ 1PN cao cấp gần sân bay Tân Sơn Nhất. Nội thất hiện đại, tầm nhìn rộng, gần nhiều nhà hàng và quán café.",
    amenities: ["Wifi", "Máy lạnh Panasonic", "Máy giặt", "Tủ lạnh", "Smart TV 55\"", "Hầm xe"],
  },
];
